src/Entity/Fruit.php
<?php

namespace App\Entity;

use App\Repository\FruitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FruitRepository::class)]
class Fruit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $family = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fruit_order = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $genus = null;

    #[ORM\Column(nullable: true)]
    private array $nutritions = [];

    #[ORM\Column]
    private ?bool $is_favourite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFamily(): ?string
    {
        return $this->family;
    }

    public function setFamily(?string $family): self
    {
        $this->family = $family;

        return $this;
    }

    public function getFruitOrder(): ?string
    {
        return $this->fruit_order;
    }

    public function setFruitOrder(?string $fruit_order): self
    {
        $this->fruit_order = $fruit_order;

        return $this;
    }

    public function getGenus(): ?string
    {
        return $this->genus;
    }

    public function setGenus(?string $genus): self
    {
        $this->genus = $genus;

        return $this;
    }

    public function getNutritions(): array
    {
        return $this->nutritions;
    }

    public function setNutritions(?array $nutritions): self
    {
        $this->nutritions = $nutritions;

        return $this;
    }

    public function getIsFavourite(): ?bool
    {
        return $this->is_favourite;
    }

    public function setIsFavourite(bool $is_favourite): self
    {
        $this->is_favourite = $is_favourite;

        return $this;
    }
}

src/Controller/FruitsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Fruit;

class FruitsController extends AbstractController
{
    #[Route('/', name: 'app_fruits')]
    public function index(EntityManagerInterface $em): Response
    {
        $fruits = $em->getRepository(Fruit::class)->findAll();
        return $this->render('fruits/index.html.twig', [
            'fruits' => $fruits,
        ]);
    }

    #[Route('/favourite-fruits', name: 'app_favourite_fruits')]
    public function favouriteFruits(EntityManagerInterface $em): Response
    {
        $fruits = $em->getRepository(Fruit::class)->getFavouriteFruits();
        return $this->render('fruits/favourite.html.twig', [
            'fruits' => $fruits,
        ]);
    }

    #[Route('/add-remove-favourite/{id}', name: 'app_add_remove_favourite')]
    public function addRemoveFavourite(EntityManagerInterface $em, $id): Response
    {
        $fruit = $em->getRepository(Fruit::class)->find($id);
        if ($fruit && $fruit->getIsFavourite() == 1) {
            $fruit->setIsFavourite(false);
            $message = $fruit->getName() . ' removed from favourite.';
        } else {

            // Check favourite fruits should not more than 10
            $favouriteFruits = $em->getRepository(Fruit::class)->getFavouriteFruits();
            if ($favouriteFruits && count($favouriteFruits) == 10) {
                return new JsonResponse([
                    'status'    => false,
                    'message'   => 'You can add a maximum of 10 fruits to your favorites.'
                ]);    
            }

            $fruit->setIsFavourite(true);
            $message = $fruit->getName() . ' added to favourite.';
        }
        $em->persist($fruit);
        $em->flush();
        return new JsonResponse([
            'status'    => true,
            'message'   => $message
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}


        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
        {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

templates/fruits/favourite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fruits | Fruitsninja{% endblock %}

{% block body %}
<div class="heading text-center mt-5 mb-5">
  <h1>My Favourite Fruits</h1>
</div>
<div class="mb-2"> 
  <a href="{{ path('app_fruits') }}" class="btn btn-warning">Back</a>
</div>
<div id="alert-msg"></div>
<table class="table" id="myTable">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Family</th>
      <th scope="col">Order</th>
      <th scope="col">Genus</th>
    </tr>
  </thead>
  <tbody>
    {% set totalCalories = 0 %}
    {% set totalFat = 0 %}
    {% set totalSugar = 0 %}
    {% set totalCarbohydrates = 0 %}
    {% set totalProtein = 0 %}
    {% if fruits %}
      {% for fruit in fruits %}
        {% set totalCalories = totalCalories + fruit.nutritions.calories %}
        {% set totalFat = totalFat + fruit.nutritions.fat %}
        {% set totalSugar = totalSugar + fruit.nutritions.sugar %}
        {% set totalCarbohydrates = totalCarbohydrates + fruit.nutritions.carbohydrates %}
        {% set totalProtein = totalProtein + fruit.nutritions.protein %}
      <tr>
        <td>{{ fruit.name }}</td>
        <td>{{ fruit.family }}</td>
        <td>{{ fruit.fruitOrder }}</td>
        <td>{{ fruit.genus }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="5" class="text-center">No favourite fruits found.</td>
      </tr>
    {% endif %}
  </tbody>
</table>

<h3 class="mt-5">Total Nutritions</h3>
<table class="table">
  <thead>
    <tr>
      <th>Calories</th>
      <th>Fat</th>
      <th>Sugar</th>
      <th>Carbohydrates</th>
      <th>Protein</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ totalCalories }}</td>
      <td>{{ totalFat }}</td>
      <td>{{ totalSugar }}</td>
      <td>{{ totalCarbohydrates }}</td>
      <td>{{ totalProtein }}</td>
    </tr>
  </tbody>
</table>

{% endblock %}

templates/fruits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fruits | Fruitsninja{% endblock %}

{% block body %}
<div class="heading text-center mt-5 mb-5">
  <h1>Fruits</h1>
</div>
<div class="mb-2"> 
  <a href="{{ path('app_favourite_fruits') }}" class="btn btn-warning">My Favourite Fruits</a>
</div>
<div id="alert-msg"></div>
<table class="table" id="myTable">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Family</th>
      <th scope="col">Order</th>
      <th scope="col">Genus</th>
      <th scope="col" width="15%">Action</th>
    </tr>
  </thead>
  <tbody>
    {% if fruits %}
      {% for fruit in fruits %}
      <tr>
        <td>{{ fruit.name }}</td>
        <td>{{ fruit.family }}</td>
        <td>{{ fruit.fruitOrder }}</td>
        <td>{{ fruit.genus }}</td>
        <td data-id="{{ fruit.id }}">
          {% set displayAddFavouriteBtn = true %}
          {% if fruit.isFavourite %}
            {% set displayAddFavouriteBtn = false %}
          {% endif %}
          <button class="btn btn-sm btn-success favourite-btn add-favourite {% if displayAddFavouriteBtn == false %} d-none {% endif %}" id="add-favourite-{{ fruit.id }}" data-link="{{ path('app_add_remove_favourite', {'id': fruit.id}) }}"><i class="fa fa-add"></i>Add To Favourite</button>
          <button class="btn btn-sm btn-danger favourite-btn remove-favourite {% if displayAddFavouriteBtn == true %} d-none {% endif %}" id="remove-favourite-{{ fruit.id }}" data-link="{{ path('app_add_remove_favourite', {'id': fruit.id}) }}"><i class="fa fa-add"></i>Remove Favourite</button>
        </td>
      </tr>
      {% endfor %}
    {% endif %}
  </tbody>
</table>
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
$(document).ready(function () {
  $('#myTable').DataTable();

  // Add Remove Favourite
  $(document).on('click', ".favourite-btn", function(){

    var recordId = $(this).parent().data('id');
    var url = $(this).data('link');
    var id = $(this).attr('id');
    $("#"+id).prop('disabled', true);
    $.ajax({
      method: "GET",
      url: url,
      success: (result) => {
        $(this).prop('disabled', false);
        if (result.status == true) {

          // hide show button
          if ($(this).hasClass('add-favourite')) {
            $(this).parent().find('.remove-favourite').removeClass('d-none');
            $(this).addClass('d-none');
          } else if ($(this).hasClass('remove-favourite')) {
            $(this).parent().find('.add-favourite').removeClass('d-none');
            $(this).addClass('d-none');
          }
          
          $("#alert-msg").html('<div class="alert alert-success" role="alert">'+result.message+'</div>');
        } else {
          $("#alert-msg").html('<div class="alert alert-danger" role="alert">'+result.message+'</div>');
        }

        $(".alert").delay(2000).slideUp(200, function() {
          $(this).alert('close');
        });
      },
      error: (xhr,status,error) => {
        $(this).prop('disabled', false);
        $("#alert-msg").html('<div class="alert alert-danger" role="alert">Oops something went wrong. Please try again.</div>');

        $(".alert").delay(2000).slideUp(200, function() {
          $(this).alert('close');
        });
      }
    });
  });

});
</script>
{% endblock %}